namespace Hand2Note.Api
{
    /// <summary>
    /// Supported poker rooms
    /// </summary>
    public enum Rooms
    {
        Unrecognized = 0,
        PokerStars = 10,
        Pacific = 14,
        IPoker = 13,
        PartyPoker = 11,
        WinningPokerNetwork = 15,
        Winamax = 9,
        Microgaming = 7,
        Baazi = 1,
        CheckRaise = 2,
        Dollaro = 12,
        BetSense = 3,
        MonkeyBet = 4,
        Fulpot = 5,
        GGNet = 16,
        EnetPoker = 17,
        KlasPoker = 18,
        PokerWorld = 19,
        Ourgame = 20,
        BetOnline = 21,
        BIGBETGE = 22,
        BluffOnline = 23,
        BluffDaddy = 24,
        ColombiaPokerLive = 25,
        EuropeBetCom = 26,
        FTRPoker = 27,
        PokerGDFPLAY = 28,
        Highrollers = 29,
        ItalyLivePoker = 30,
        PokerMania = 31,
        PokerMIRA = 32,
        PokerDom = 33,
        Pokermatch = 34,
        RedArgentinaDePoker = 35,
        SekaBETCom = 36,
        Sekabet = 37,
        SpartanPokerCom = 38,
        SportsBetting = 39,
        TigerGaming = 40,
        VenezuelaPokerLive = 41,
        XMaster = 42,
        PokerGrant = 43,
        GrandPokerEu = 44,
        Revolutionbets = 45,
        Vbet = 46,
        Win2Day = 47,
        WWin = 48,
        PokerMaster = 49,
        PlanetWin365 = 50,
        AconcaguaPoker = 51,
        BrasilPokerLive = 52,
        SurPokerDeLasAmericas = 53,
        ChilePokerLive = 54,
        BoliviaPokerLive = 55,
        CostaRicaPokerLive = 56,
        GuaraniPokerLive = 57,
        MexicoPokerLive = 58,
        PeruPokerLive = 59,
        PPPoker = 60,
        PokerKingdom = 61,
        PokerKing = 62,
        FishPokers = 63,
        OhPoker = 64,
        OnePS = 65,
        PokerClans = 66,
        KKPoker = 67
    }
}